import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { defaultLocale } from "@/lib/i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jakarta = Plus_Jakarta_Sans({
  weight:['500','800'],
  subsets: ['latin'],
})

export default async function RootLayout({
  children,
  params: {lang},
}: {
  children: React.ReactNode;
  params:{lang:string[] | undefined}
}) {
  return (
    <html 
      lang={(lang && lang[0]) || defaultLocale} 
      className={jakarta.className}
    >
      <body>
        <div className="w-full min-h-svh text-base-content bg-base-100">
          <Navbar/>
          <div className="px-5">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
