CREATE TABLE user_credits (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自动生成的唯一主键
    user_id            VARCHAR(255) NOT NULL,                                -- Clerk 分配的唯一用户 ID
    free_credits_total INTEGER DEFAULT 0 NOT NULL,                           -- 用户的总免费点数
    free_credits_used  INTEGER DEFAULT 0 NOT NULL,                           -- 用户已使用的免费点数
    paid_credits_total INTEGER DEFAULT 0,                                    -- 用户的总付费点数
    paid_credits_used  INTEGER DEFAULT 0,                                    -- 用户已使用的付费点数
    updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL       -- 最后一次更新点数的时间
);

-- 表注释
COMMENT ON TABLE user_credits IS '用户点数记录表';

-- 字段注释
COMMENT ON COLUMN user_credits.user_id IS 'Clerk 分配的唯一用户 ID';
COMMENT ON COLUMN user_credits.free_credits_total IS '用户的总免费点数';
COMMENT ON COLUMN user_credits.free_credits_used IS '用户已使用的免费点数';
COMMENT ON COLUMN user_credits.paid_credits_total IS '用户的总付费点数';
COMMENT ON COLUMN user_credits.paid_credits_used IS '用户已使用的付费点数';
COMMENT ON COLUMN user_credits.updated_at IS '最后更新点数的时间';