
CREATE TABLE user_info (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自动生成的唯一主键
    user_id       VARCHAR(255) NOT NULL UNIQUE,                         -- Clerk 分配的唯一用户 ID
    first_name    VARCHAR(255),                                         -- 用户的名字
    last_name     VARCHAR(255),                                         -- 用户的姓氏（如果有的话）
    email         VARCHAR(255) NOT NULL,                                -- 用户的邮箱地址
    image_url     VARCHAR(1024),                                        -- 用户头像 URL
    last_login_at TIMESTAMP WITH TIME ZONE,                             -- 用户最后一次登录的时间
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,      -- 用户在系统中的创建时间
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL       -- 用户信息最后一次更新的时间
);

-- 表注释
COMMENT ON TABLE user_info IS '用户基本信息表';

-- 字段注释
COMMENT ON COLUMN user_info.user_id IS 'Clerk 分配的唯一用户 ID';
COMMENT ON COLUMN user_info.first_name IS '用户名字';
COMMENT ON COLUMN user_info.last_name IS '用户姓氏';
COMMENT ON COLUMN user_info.email IS '用户邮箱地址';
COMMENT ON COLUMN user_info.image_url IS '用户头像 URL';
COMMENT ON COLUMN user_info.last_login_at IS '用户最后一次登录时间';
COMMENT ON COLUMN user_info.created_at IS '创建时间';
COMMENT ON COLUMN user_info.updated_at IS '更新时间';